// metro.config.js
const { getDefaultConfig } = require('expo/metro-config');
const path = require('path');
const fs = require('fs');

const config = getDefaultConfig(__dirname);

// ─── Find the real expo-web-browser entry point via Node require.resolve ─────
// This runs in Node (not Metro), so it bypasses our custom resolver and
// will never cause infinite recursion.
let realWebBrowserEntry;
try {
  realWebBrowserEntry = require.resolve('expo-web-browser');
} catch (_) {
  realWebBrowserEntry = null;
}

// ─── Write a shim that hard-codes the absolute path to the real package ───────
// The shim is regenerated every time Metro starts, so it always points to the
// correct pnpm/npm path — no guessing, no circular requires.
const shimDir = path.resolve(__dirname, 'shims');
const shimPath = path.resolve(shimDir, 'expo-web-browser-resolved.js');

if (!fs.existsSync(shimDir)) {
  fs.mkdirSync(shimDir, { recursive: true });
}

if (realWebBrowserEntry) {
  fs.writeFileSync(
    shimPath,
    [
      '// Auto-generated by metro.config.js — do not edit.',
      `const real = require(${JSON.stringify(realWebBrowserEntry)});`,
      "if (typeof real.maybeCompleteAuthSession !== 'function') {",
      "  real.maybeCompleteAuthSession = function() { return { type: 'success' }; };",
      '}',
      'module.exports = real;',
    ].join('\n'),
    'utf8'
  );
} else {
  // Fallback: no real package found — export safe stubs
  fs.writeFileSync(
    shimPath,
    [
      '// Fallback shim — expo-web-browser not found in this environment.',
      'module.exports = {',
      "  maybeCompleteAuthSession: function() { return { type: 'success' }; },",
      "  openAuthSessionAsync: async function() { return { type: 'cancel' }; },",
      "  openBrowserAsync: async function() { return { type: 'cancel' }; },",
      '  dismissBrowser: function() {},',
      '  dismissAuthSession: function() {},',
      '  warmUpAsync: async function() {},',
      '  coolDownAsync: async function() {},',
      '};',
    ].join('\n'),
    'utf8'
  );
}

// ─── Intercept ALL expo-web-browser imports ───────────────────────────────────
// resolveRequest works with pnpm symlinks (unlike extraNodeModules).
const originalResolveRequest = config.resolver.resolveRequest;
config.resolver.resolveRequest = (context, moduleName, platform) => {
  if (moduleName === 'expo-web-browser') {
    return { filePath: shimPath, type: 'sourceFile' };
  }
  if (originalResolveRequest) {
    return originalResolveRequest(context, moduleName, platform);
  }
  return context.resolveRequest(context, moduleName, platform);
};

module.exports = config;
