name: Build Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install EAS CLI
        run: npm install -g eas-cli@latest

      - name: Install deps
        run: |
          npm install --legacy-peer-deps --force
          npm install ajv@^8 --legacy-peer-deps --force

      - name: Build APK
        run: eas build -p android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_PROJECT_ID: souqqalqilia
          EXPO_ACCOUNT_NAME: eyadfadezh499s-organization
