name: Build Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install deps
        run: |
          npm install --legacy-peer-deps
          npm install ajv@^8 ajv-keywords@^5 --legacy-peer-deps

      - name: Fix expo config
        run: npx expo install --fix

      - name: Build APK
        run: eas build -p android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_PROJECT_ID: souqqalqilia
          EXPO_ACCOUNT_NAME: eyadfadezh499s-organization
