name: Build Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install EAS CLI
        run: npm install -g eas-cli@latest

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps --force
          npm install ajv@^8 --legacy-peer-deps --force

      - name: Initialize EAS project (Non-interactive)
        # هذا الأمر مهم جداً لربط المشروع
        run: eas init --id ${{ secrets.EXPO_PROJECT_ID }} --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build APK
        run: eas build -p android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
